spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
      routes:
        - id: ReportingService
          uri: /ReportingService
          predicates: 
            - Path=/report/**

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
