server:
  port: 8384

spring:
  #zipkin:
    #base-url: http://localhost:9411/

  kafka:
    application-id: scoringservice
    window-size: 5
    
  cloud:
    compatibility-verifier:
      enabled: false

#sleuth:
  #sampler:
    #probability: 1

logging:
  level:
    root: ERROR
  org.springframework: ERROR
